" Chris Sun's vimrc file
" An example for a vimrc file.
"
" Current plugins installed
" A way to manage 'runtimepath' and vim plugins
" https://github.com/tpope/vim-pathogen
" Keyboard shortcuts for Rails, rake, rspec
" https://github.com/tpope/vim-rails
" SnipMate
" http://www.vim.org/scripts/script.php?script_id=2540
" Quickly comment out a section of code
" https://github.com/tomtom/tcomment_vim
" % key can find matching if/else/end, def/end, class/end, etc.
" https://github.com/edsono/vim-matchit

" Needed for pathogen.vim
" See https://github.com/tpope/vim-pathogen
execute pathogen#infect()

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" No backup files (a.txt~) or swap files
set nobackup

" For swap files (a.txt.swp), place them in the /tmp directory
set directory=/tmp

" Make tabs only 2 spaces.
set expandtab
set tabstop=2 
set softtabstop=2 
set shiftwidth=2

" Set the tag file
set tags=./tags;

" Make the background black and the foreground white
set background=dark

" Show line numbers on left column
set number

" Enable file type detection and use language-dependent indenting.
filetype plugin indent on

" To navigate between VIM windows, normal one uses
" Ctrl-w then (h,j,k,l or arrow keys)
" instead use Ctrl-h, Ctrl-j, Ctrl-k, Ctrl-l
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Open new split panes to right and bottom, which feels more natural than
" Vim’s default:
set splitbelow
set splitright

" For the autoTag.vim plugin to work
" need to source the file
" source autoTag.vim
"

" Use ack as the program for searching
" Download from http://beyondgrep.com/
set grepprg=ack

" Assigning the leader key
let mapleader = ","

" Alias ,cc for the :TComment command which comments out lines
map <Leader>cc :TComment<CR> 

" Since the rails-vim plugin is installed, have some aliases
" for common commands
map <Leader>u :Runittest<cr>
map <Leader>vc :RVcontroller<cr>
map <Leader>vf :RVfunctional<cr>
map <Leader>vu :RVunittest<CR>
map <Leader>vm :RVmodel<cr>
map <Leader>vv :RVview<cr>

" taken from r00k's vimrc
" open the vimrc
map <Leader>vi :tabe ~/.vimrc<CR>

" case-insensitve search
set ignorecase
" case-senstivie search if search pattern has uppercase letters
set smartcase

function! ToggleNumMode()
  if(&rnu == 1)
    set nu
  else
    set rnu
  endif
endfunc

" Toggle between relative and absolute line numbers
nnoremap <Leader>n :call ToggleNumMode()<CR>
